### ISSUE TITLE
Output Topic - not coming out

### ISSUE THREAD

**Issue by tsprivate** [linuxha/node-red-contrib-mytimeout#16]
Hi ,
I'm using your timer for many flows. I had not used the "Output topic" before but in my current flow it does not come to the output and I have to set the "topic" manually. A debug-node was showing empty Topic content. 
I'm using your latest version and the node node-red-contrib-simple-gate

![image](https://user-images.githubusercontent.com/41630517/46577233-98299080-ca2d-11e8-9a75-86c7ba4799ab.png)

`[{"id":"49c07f1b.63b48","type":"gate","z":"ebaeea0a.a6df68","name":"","controlTopic":"control","defaultState":"open","openCmd":"open","closeCmd":"close","toggleCmd":"toggle","defaultCmd":"default","x":650,"y":240,"wires":[["3bccad86.0811b2","9d9fed9b.0875f"]]},{"id":"9d9fed9b.0875f","type":"mytimeout","z":"ebaeea0a.a6df68","name":"outage","outtopic":"control","outsafe":"close","outwarning":"","outunsafe":"Open","warning":"5","timer":"3600","debug":false,"ndebug":false,"ignoreCase":false,"repeat":false,"again":false,"x":630,"y":180,"wires":[["2864c9f4.bd6b66"],[]]},{"id":"2864c9f4.bd6b66","type":"change","z":"ebaeea0a.a6df68","name":"ctrl","rules":[{"t":"set","p":"topic","pt":"msg","to":"control","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":750,"y":180,"wires":[["49c07f1b.63b48"]]},{"id":"3bccad86.0811b2","type":"function","z":"ebaeea0a.a6df68","name":"Set temp","func":"var temp1 = parseInt(msg.payload.tempc);\nvar speed = parseInt((msg.payload.windspeed)*3.6);\nmsg.payload.tempc = temp1;\nmsg.payload.windspeed = speed;\nreturn (msg);","outputs":1,"noerr":0,"x":810,"y":240,"wires":[["791b24dd.eb735c"]]}]`

**Comment by linuxha** [comment]
I'm a bit behind on this code, I'll need to see where this fits with the other bug fix and the feature request. Sorry about that.

**Comment by tsprivate** [comment]
No worries, the workaround with the the change-node (to set the topic) after your timer does work

**Comment by linuxha** [comment]
I did another update for an updated README (corrections) and the npm version. One of these days I'll get it straight in my head how to use github. I've pushed 3.1.0 to npm. Sorry I forgot about this (since last Oct) been busy at work. I'm hoping that will slow down a bit now but it doesn't look like it will.

**Comment by linuxha** [comment]
Found that the topic (and other attributes) are on most messages. Working on getting them on all output  1 messages.

**Comment by linuxha** [comment]
This has passed my test suite where topic (and extra attributes) are in all the output 1 msgs. I'm going close this.
