### ISSUE TITLE
First countdown msg is a string !

### ISSUE THREAD

**Issue by ipa64** [linuxha/node-red-contrib-mytimeout#17]
Hello,
I get a strange behavior, on second output for the countdown the first sent msg is a string then all next are number than expected. Below a debug log, for a timeout of 600s.
It’s not a big issue, just the first value are not displayed on the dashboard.
Thank you

18.07.2019 à 15:06:13node: MyTimeout
msg.payload : string[3]
"600"
18.07.2019 à 15:06:13node: MyTimeout
msg.payload : number
599
—-> all next output are number format

**Comment by linuxha** [comment]
I think I know what is doing this. Let me see if I can replicate this first. Do you have some sample code?

**Comment by ipa64** [comment]
Yes of course
Thank you for you support
Have a nice day
Patrick


[{"id":"cde7d480.58646","type":"ui_button","z":"86d2e7e0.33e408","name":"","group":"7b600330.aafcac","order":9,"width":"2","height":"2","passthru":false,"label":"Auto","tooltip":"","color":"","bgcolor":"Blue","icon":"","payload":"on","payloadType":"str","topic":"","x":140.51153182983398,"y":490.68400955200195,"wires":[["58f824c3.de8414"]]},{"id":"5fef09a6.835c18","type":"ui_button","z":"86d2e7e0.33e408","name":"","group":"7b600330.aafcac","order":10,"width":"2","height":"2","passthru":false,"label":"Reset","tooltip":"","color":"","bgcolor":"","icon":"","payload":"stop","payloadType":"str","topic":"","x":141.00037002563477,"y":645.4961452484131,"wires":[["58f824c3.de8414","ed63e76f.89176","5d62d535.b2626c"]]},{"id":"58f824c3.de8414","type":"function","z":"86d2e7e0.33e408","name":"Start","func":"if (msg.payload===\"on\"){\n    node.send({payload: \"stop\"}); // reset avant  \n    var mydelay=flow.get(\"myDelay\"); // recupere la valeur selectionnee\n    if (mydelay===undefined) mydelay=5; // Si aucune valeur\n    msg.timeout = \"\"+mydelay; // payload delay\n    return [msg];\n} else { // Si pas Auto c’est reset\n    return msg;\n}","outputs":1,"noerr":0,"x":311.7033157348633,"y":491.0000419616699,"wires":[["f935494b.3e6b28","d97080a4.8e07e"]]},{"id":"f935494b.3e6b28","type":"mytimeout","z":"86d2e7e0.33e408","name":"","outtopic":"","outsafe":"on","outwarning":"warning","outunsafe":"off","warning":"5","timer":"30","debug":false,"ndebug":false,"ignoreCase":false,"repeat":false,"again":false,"x":455.5,"y":491,"wires":[["173b9142.300aaf","ed63e76f.89176"],["9133cb8a.de803","a56d26a4.00c428"]]},{"id":"173b9142.300aaf","type":"change","z":"86d2e7e0.33e408","name":"stop","rules":[{"t":"change","p":"payload","pt":"msg","from":"stop","fromt":"str","to":"off","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":621.5,"y":483,"wires":[["76a34a5.415d334"]]},{"id":"ed63e76f.89176","type":"function","z":"86d2e7e0.33e408","name":"StartNext","func":"if (msg.payload===\"stop\"){\n    return [msg];\n}\nif (msg.payload===\"off\"){\n    node.send({payload: \"stop\"}); // reset avant  \n    var mydelay=flow.get(\"myDelay\"); // recupere la valeur selectionnee\n    if (mydelay===undefined) mydelay=5; // Si aucune valeur\n    msg.timeout = \"\"+mydelay; // payload delay\n    msg.payload=\"on\";\n    return [msg];\n} else {\n    return null;\n}","outputs":1,"noerr":0,"x":650,"y":575,"wires":[["e543812.90efd8","6018ddee.012dcc"]]},{"id":"e543812.90efd8","type":"mytimeout","z":"86d2e7e0.33e408","name":"","outtopic":"","outsafe":"on","outwarning":"warning","outunsafe":"off","warning":"5","timer":"30","debug":false,"ndebug":false,"ignoreCase":false,"repeat":false,"again":false,"x":817,"y":575,"wires":[["58a55e5b.f3103","5d62d535.b2626c"],["bae76ef9.41be38"]]},{"id":"58a55e5b.f3103","type":"change","z":"86d2e7e0.33e408","name":"stop","rules":[{"t":"change","p":"payload","pt":"msg","from":"stop","fromt":"str","to":"off","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":985,"y":569,"wires":[["8e66cfea.11fe1"]]},{"id":"5d62d535.b2626c","type":"function","z":"86d2e7e0.33e408","name":"StartNext","func":"if (msg.payload===\"stop\"){\n    return [msg];\n}\nif (msg.payload===\"off\"){\n    node.send({payload: \"stop\"}); // reset avant  \n    var mydelay=flow.get(\"myDelay\"); // recupere la valeur selectionnee\n    if (mydelay===undefined) mydelay=5; // Si aucune valeur\n    msg.timeout = \"\"+mydelay; // payload delay\n    msg.payload=\"on\";\n    return [msg];\n} else {\n    return null;\n}","outputs":1,"noerr":0,"x":984,"y":647,"wires":[["b682c94f.c20ba8"]]},{"id":"b682c94f.c20ba8","type":"mytimeout","z":"86d2e7e0.33e408","name":"","outtopic":"","outsafe":"on","outwarning":"warning","outunsafe":"off","warning":"5","timer":"30","debug":false,"ndebug":false,"ignoreCase":false,"repeat":false,"again":false,"x":1135.9999771118164,"y":646.0000190734863,"wires":[["7d6be48.a88581c"],["ea9e4ed4.9a1908"]]},{"id":"7d6be48.a88581c","type":"change","z":"86d2e7e0.33e408","name":"stop","rules":[{"t":"change","p":"payload","pt":"msg","from":"stop","fromt":"str","to":"off","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1304,"y":640,"wires":[["5b8b4b80.08c374"]]},{"id":"2383d481.6fdfa4","type":"ui_text","z":"86d2e7e0.33e408","group":"7b600330.aafcac","order":4,"width":"3","height":"1","name":"T1","label":"mm:ss","format":"{{msg.payload}}","layout":"row-left","x":1030.5,"y":519,"wires":[]},{"id":"5dece104.172eb","type":"ui_text","z":"86d2e7e0.33e408","group":"7b600330.aafcac","order":6,"width":"3","height":"1","name":"T2","label":"mm:ss","format":"{{msg.payload}}","layout":"row-left","x":1397,"y":603,"wires":[]},{"id":"449aa534.7e45fc","type":"ui_text","z":"86d2e7e0.33e408","group":"7b600330.aafcac","order":8,"width":"3","height":"1","name":"T3","label":"mm:ss","format":"{{msg.payload}}","layout":"row-left","x":1721,"y":680,"wires":[]},{"id":"9133cb8a.de803","type":"change","z":"86d2e7e0.33e408","name":"Filtre","rules":[{"t":"change","p":"payload","pt":"msg","from":"-1","fromt":"num","to":"0","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":622.5,"y":519,"wires":[["94ad8111.849418"]]},{"id":"bae76ef9.41be38","type":"change","z":"86d2e7e0.33e408","name":"Filtre","rules":[{"t":"change","p":"payload","pt":"msg","from":"-1","fromt":"num","to":"0","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":987,"y":605,"wires":[["4ee96cf8.e184b4"]]},{"id":"ea9e4ed4.9a1908","type":"change","z":"86d2e7e0.33e408","name":"Filtre","rules":[{"t":"change","p":"payload","pt":"msg","from":"-1","fromt":"num","to":"0","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":1305,"y":681,"wires":[["fe6a954a.d23718"]]},{"id":"9dbce29a.4a742","type":"moment","z":"86d2e7e0.33e408","name":"s2hms","topic":"","input":"payload","inputType":"msg","inTz":"Etc/UTC","adjAmount":0,"adjType":"days","adjDir":"add","format":"mm:ss","locale":"POSIX","output":"payload","outputType":"msg","outTz":"Etc/UTC","x":905.5,"y":519,"wires":[["2383d481.6fdfa4"]]},{"id":"94ad8111.849418","type":"change","z":"86d2e7e0.33e408","name":"To millisecs","rules":[{"t":"set","p":"payload","pt":"msg","to":"msg.payload*1000","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":764,"y":519,"wires":[["9dbce29a.4a742"]]},{"id":"4ee96cf8.e184b4","type":"change","z":"86d2e7e0.33e408","name":"To millisecs","rules":[{"t":"set","p":"payload","pt":"msg","to":"msg.payload*1000","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":1128.0000457763672,"y":605.111081123352,"wires":[["2c3b5032.7f4f6"]]},{"id":"fe6a954a.d23718","type":"change","z":"86d2e7e0.33e408","name":"To millisecs","rules":[{"t":"set","p":"payload","pt":"msg","to":"msg.payload*1000","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":1444,"y":681,"wires":[["3184d679.a841d2"]]},{"id":"2c3b5032.7f4f6","type":"moment","z":"86d2e7e0.33e408","name":"s2hms","topic":"","input":"payload","inputType":"msg","inTz":"Etc/UTC","adjAmount":0,"adjType":"days","adjDir":"add","format":"mm:ss","locale":"POSIX","output":"payload","outputType":"msg","outTz":"Etc/UTC","x":1270.999942779541,"y":605.2221918106079,"wires":[["5dece104.172eb"]]},{"id":"3184d679.a841d2","type":"moment","z":"86d2e7e0.33e408","name":"s2hms","topic":"","input":"payload","inputType":"msg","inTz":"Etc/UTC","adjAmount":0,"adjType":"days","adjDir":"add","format":"mm:ss","locale":"POSIX","output":"payload","outputType":"msg","outTz":"Etc/UTC","x":1589,"y":681,"wires":[["449aa534.7e45fc"]]},{"id":"76a34a5.415d334","type":"mqtt out","z":"86d2e7e0.33e408","name":"Relay2","topic":"cmnd/arrosage/Power2","qos":"","retain":"","broker":"843d5571.c5ca2","x":747.7777328491211,"y":482.2221803665161,"wires":[]},{"id":"8e66cfea.11fe1","type":"mqtt out","z":"86d2e7e0.33e408","name":"Relay3","topic":"cmnd/arrosage/Power3","qos":"","retain":"","broker":"843d5571.c5ca2","x":1109.999948501587,"y":568.888897895813,"wires":[]},{"id":"5b8b4b80.08c374","type":"mqtt out","z":"86d2e7e0.33e408","name":"Relay4","topic":"cmnd/arrosage/Power4","qos":"","retain":"","broker":"843d5571.c5ca2","x":1424.44437789917,"y":640.0000047683716,"wires":[]},{"id":"d97080a4.8e07e","type":"function","z":"86d2e7e0.33e408","name":"stop","func":"if (msg.payload===\"stop\") return msg;\nreturn null;","outputs":1,"noerr":0,"x":442.6482238769531,"y":544.0081691741943,"wires":[["ed63e76f.89176"]]},{"id":"6018ddee.012dcc","type":"function","z":"86d2e7e0.33e408","name":"stop","func":"if (msg.payload===\"stop\") return msg;\nreturn null;","outputs":1,"noerr":0,"x":807.4041137695312,"y":621.3900146484375,"wires":[["5d62d535.b2626c"]]},{"id":"a56d26a4.00c428","type":"debug","z":"86d2e7e0.33e408","name":"debug2","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":641.428596496582,"y":435.7142915725708,"wires":[]},{"id":"7b600330.aafcac","type":"ui_group","z":"","name":"Test Marcel","tab":"648488f2.64feb","order":3,"disp":true,"width":"6","collapse":false},{"id":"843d5571.c5ca2","type":"mqtt-broker","z":"","name":"Mosquitto","broker":"192.168.1.100","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthRetain":"false","birthPayload":"","closeTopic":"","closeQos":"0","closeRetain":"false","closePayload":"","willTopic":"","willQos":"0","willRetain":"false","willPayload":""},{"id":"648488f2.64feb","type":"ui_tab","z":"","name":"Test V2","icon":"dashboard","order":1,"disabled":false,"hidden":false}]

**Comment by ipa64** [comment]
a simpler way to test

`[{"id":"df7e7f91.a03e88","type":"mytimeout","z":"96df24ce.ad049","name":"","outtopic":"","outsafe":"on","outwarning":"Warning","outunsafe":"off","warning":"5","timer":"30","debug":false,"ndebug":false,"ignoreCase":false,"repeat":false,"again":false,"x":527,"y":186,"wires":[[],["44a6f85c.461be8"]]},{"id":"eb745f5d.232e8","type":"inject","z":"96df24ce.ad049","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":186,"wires":[["7b71d50b.fba024"]]},{"id":"44a6f85c.461be8","type":"debug","z":"96df24ce.ad049","name":"debug","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":738,"y":192,"wires":[]},{"id":"7b71d50b.fba024","type":"function","z":"96df24ce.ad049","name":"Start","func":"mydelay=5; \nmsg.timeout = \"10\";\nmsg.payload = \"on\";\nreturn msg;","outputs":1,"noerr":0,"x":354,"y":186,"wires":[["df7e7f91.a03e88"]]}]`

![](https://media.joomeo.com/medium/5d31a01b9b83b.jpg)
![](https://media.joomeo.com/medium/5d31a0381538e.jpg)

**Comment by linuxha** [comment]
I think the above is a different code, I see looping and a gate. I don't have the gate but I'll see what I can figure out.

**Comment by linuxha** [comment]
I setup my docker node-red dev container and I ran the code. I'm pretty sure I resolved the issue with the first msg containing a string and the rest a number. They should now all contain just numbers.

Let me know what you think and I'll close this.

**Comment by ipa64** [comment]
Yes now it's working :-)
Thank you for all !

**Comment by linuxha** [comment]
Thanks, I'll close this issue now.
