### ISSUE TITLE
stop or cancel not working

### ISSUE THREAD

**Issue by totomaze** [linuxha/node-red-contrib-mytimeout#3]
Version node-red-contrib-mytimeout@1.0.15
When I send the following payload when a timer is already started , the countdown freeze and does not send a cancel payload
{
    "payload": "cancel"
}

Also your documentation is wrong its 'timer' instead of 'timeoute'

Thanks for your job

**Comment by linuxha** [comment]
I'm aware of the issue with the freeze, I am working on it. I have a rewrite and a few of the features are not quite there yet.

The bug fix will have a few more fixes but it will be using timeout not timer. That's just the direction I went.

**Comment by linuxha** [comment]
I've updated the git repo and I see the npm publish on https://www.npmjs.com/package/node-red-contrib-mytimeout but I can't find the update on https://flows.nodered.org/. There, it still shows up as 1.0.15. I'm working to resolve this in the discord.

**Comment by linuxha** [comment]
I believe that this issue has been fixed. Since I've not seen an update since July 9th I'm assuming that the current issue is resolved. If this issue reappears, reopen the issue of open a new issue and I'll work to resolve it then. Thanks
