### ISSUE TITLE
unwanted starting of countdown

### ISSUE THREAD

**Issue by tita2000** [linuxha/node-red-contrib-mytimeout#31]
Everytime I restart the node red server the countdown of mytimeout starts and puts a "1" on the output. I'm working with ubuntu 20.04.2 LTS, Node-RED 1.2.3 and mytimeout 3.2.0. Any help on this is appreciated. Thanks

**Comment by linuxha** [comment]
Sorry about the delay, I'll need to look into that. Some variable must be uninitialized or initialized incorrectly.

**Comment by linuxha** [comment]
Okay I setup a very simple timer, Input -> mytimeout (default settings) -> Debug (Output1), Debug (Output2). I deploy and I see no message on the debug console. I restart node-red, same result. Can I see a copy of your flow?

**Comment by tita2000** [comment]
Hi,

this is a picture of the flow. [https://ibb.co/C83thLX](url)

This is the function content:
`if (msg.payload == "1") {
    var temp = global.get('WZSSFL', "file");
    msg = { "payload": "on", "timeout": temp, "warning": 0 };
    return msg;
}  
return null;
`
ok. what it does
If I press the button 'Sonnenschutz' my windows shutters will move a defined time down. This information is provided in the variable WZSSFL. I already deleted the wire from the functions to the mytimeout nodes, but a restart of node-red started the mytimeout counter without any input.

Regards Timo

**Comment by linuxha** [comment]
I've not been able to reproduce the issue you saw but I have a idea. Hopefully I can test my idea this weekend, I think the issue is with the setup of the MQTT input topic. Do you have retain on? If you retain the data it will be published when you startup.

**Comment by tita2000** [comment]
ok, that's a hint, as all my mqtt messages are retain messages. I will try without retain and report. Regards Timo
