### ISSUE TITLE
Timer stop counting down occasionally

### ISSUE THREAD

**Issue by tsprivate** [linuxha/node-red-contrib-mytimeout#5]
Hi I have changed all my timers to your mytimeout timer, and it usually works perfectly.

Frequently , the countdown stops counting down (still showing Running: 45). I had established debug pointers before and after the timer but there was no event/trigger to halt the countdown... it just stopped

Below is a code component I use to trigger my lights and keep them running for period of time.

`[{"id":"72b956bb.e1eac8","type":"link in","z":"e9a592e9.83a77","name":"Light GW","links":["d7f70ea2.d4ba7","8ae0c979.c11a78"],"x":75,"y":760,"wires":[["b519e69a.1ea468"]]},{"id":"b519e69a.1ea468","type":"change","z":"e9a592e9.83a77","name":"GW light","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\"data\":{\"entity_id\":\"light.gateway_light_f0b4299aaf29\"}}","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":220,"y":760,"wires":[["cfec39ae.d15d08"]]},{"id":"cfec39ae.d15d08","type":"api-call-service","z":"e9a592e9.83a77","name":"Light ON","server":"8ad970d8.e2b73","service_domain":"light","service":"turn_on","data":"","mergecontext":"none","x":400,"y":760,"wires":[["a796d525.2bf298","4bd58b26.da5fa4"]],"icon":"node-red-contrib-home-assistant/arrow-right-bold-hexagon-outline.png"},{"id":"a796d525.2bf298","type":"change","z":"e9a592e9.83a77","name":"House Light timer","rules":[{"t":"set","p":"timeout","pt":"msg","to":"House_Light_timer","tot":"global"},{"t":"set","p":"payload","pt":"msg","to":"ON","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":590,"y":760,"wires":[["9b5bee98.fe7bb"]]},{"id":"4bd58b26.da5fa4","type":"api-current-state","z":"e9a592e9.83a77","name":"log?","server":"8ad970d8.e2b73","halt_if":"off","override_topic":true,"override_payload":true,"entity_id":"input_boolean.send_telgram_log","x":550,"y":720,"wires":[["683b250f.e1e11c"]]},{"id":"9b5bee98.fe7bb","type":"mytimeout","z":"e9a592e9.83a77","name":"timer","outtopic":"","outsafe":"on","outwarning":"Warning","outunsafe":"off","warning":"5","timer":"30","repeat":false,"again":false,"x":870,"y":760,"wires":[["4ed02376.34a5ec"],[]]},{"id":"77970856.b76e08","type":"link in","z":"e9a592e9.83a77","name":"Light GW off","links":[],"x":435,"y":720,"wires":[["a796d525.2bf298"]]},{"id":"683b250f.e1e11c","type":"change","z":"e9a592e9.83a77","name":"Telegram","rules":[{"t":"set","p":"myMessage","pt":"global","to":"Hallway light ==> ON","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":660,"y":720,"wires":[["3d105a9e.82e406"]]},{"id":"4ed02376.34a5ec","type":"switch","z":"e9a592e9.83a77","name":"off ?","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"off","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":1010,"y":760,"wires":[["a952e4aa.bb1868"]]},{"id":"2e8c5de5.fa5362","type":"change","z":"e9a592e9.83a77","name":"off","rules":[{"t":"set","p":"payload","pt":"msg","to":"0","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":870,"y":720,"wires":[["9b5bee98.fe7bb"]]},{"id":"3d105a9e.82e406","type":"link out","z":"e9a592e9.83a77","name":"Send Msg","links":["ed951e00.620ec"],"x":735,"y":720,"wires":[]},{"id":"a952e4aa.bb1868","type":"change","z":"e9a592e9.83a77","name":"GW light","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\"data\":{\"entity_id\":\"light.gateway_light_f0b4299aaf29\"}}","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":1180,"y":760,"wires":[["2b627979.32cfa6"]]},{"id":"161ab6a3.aa1b59","type":"link in","z":"e9a592e9.83a77","name":"Light GW off - now","links":["ed2201a6.5ebd2"],"x":795,"y":720,"wires":[["2e8c5de5.fa5362"]]},{"id":"2b627979.32cfa6","type":"api-call-service","z":"e9a592e9.83a77","name":"Light OFF","server":"8ad970d8.e2b73","service_domain":"light","service":"turn_off","data":"","mergecontext":"none","x":1320,"y":760,"wires":[["2554f049.add85"]],"icon":"node-red-contrib-home-assistant/arrow-right-bold-hexagon-outline.png"},{"id":"2554f049.add85","type":"api-current-state","z":"e9a592e9.83a77","name":"log?","server":"8ad970d8.e2b73","halt_if":"off","override_topic":true,"override_payload":true,"entity_id":"input_boolean.send_telgram_log","x":1450,"y":760,"wires":[["707e1a8b.9a2e64"]]},{"id":"707e1a8b.9a2e64","type":"change","z":"e9a592e9.83a77","name":"Telegram","rules":[{"t":"set","p":"myMessage","pt":"global","to":"Hallway light ==> OFF","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1580,"y":760,"wires":[["b2b43870.523a98"]]},{"id":"b2b43870.523a98","type":"link out","z":"e9a592e9.83a77","name":"Send Msg","links":["ed951e00.620ec"],"x":1675,"y":760,"wires":[]},{"id":"8ad970d8.e2b73","type":"server","z":"","name":"Home Assistant","url":"http://hassio/homeassistant","pass":"2bf95b829c8b4824987dcac37eed662a"}]`

**Comment by linuxha** [comment]
Do you know what version you have? I'm currently run on 2.1.4 (2.1 was a huge change form 1.x.x but 2.1.x+ mostly has some minor changes for testing and updates to the document). I'll branch my code for a fix and run your flow there.

**Comment by linuxha** [comment]
Okay, I've found I don't have some of your nodes. So you might need to explain a bit what it is doing. I have noticed that you are setting the msg.timeout. I using msg.payload.timeout (I send the payload via mqtt).

**Comment by tsprivate** [comment]
Hi, thanks for the quick reply.. I'm using Hass.io with Node-red and your version 2.1.4 ... the below image is showing a bit of the approach
![image](https://user-images.githubusercontent.com/41630517/43276167-247605fc-9147-11e8-9d11-554fe837a2dc.png)

I have several lights in my house which are triggered by motion sensors... than i tickle your timer and switch the light off as soon the timer has completed

the node sequence is:
1) select what light to switch on
2) use HA node to switch-on the light
3) reading a global variable which I use to keep the duration dynamic (can be selected by input_select)
4) I have added a telegram node to send a log when light is turned on (does not impact the issue and can be ignored
5) setting / tickling your timer (the below timer display halts frequently)
6) proceed only when the timer went "off"
7) select what light to switch off
8) use HA node to switch-off the light
9) check if telegram-logging is enabled
10) send telegram

**Comment by linuxha** [comment]
Not sure why the close (or what that means) but I'll keep looking into this. I know that  earlier versions when the input had errors I was seeing the updates suddenly just no longer update.

**Comment by tsprivate** [comment]
Can it be because I have several timers in parallel ?? ... Maybe they do impact each other?

I tested the sequence for a while with 1 light and 1 timer and could not see the issue. 

In my case I have dedicated a msg input (always the same, set just before the timer) .. so there should not be an input-error .. I can do a delete msg before setting the new input parameters, to ensure no wrong parameters are getting into the timer.

Great work on this ... and thanks a lot for the quick response

**Comment by linuxha** [comment]
YW, I hadn't given it a try with 2 at once. I can do that. I have a test bed with 4 timers. I can run them at the same time and see the results. Then try mixing. Let's see how that works.

**Comment by tsprivate** [comment]
I think I have about 12 individual timers running at any point of time .. and they are getting tickled/restarted and stopped randomly (e.g. motion, door closed,etc)

**Comment by linuxha** [comment]
I haven't setup the 12 timers yet, but I wonder if having them the same name (Timer) is causing it an issue. They are in the same flow. The name space part of node-red/javascript does confuse me

I'll setup the 12 timers later tonight with a test script and then proceed to abuse it. I'll start out with the same name and set the timers to 90 seconds. I may also add a debug flag so I can easily turn off the log messages. That might be putting too much of a load on the machine. At the moment this is just guessing.

**Comment by tsprivate** [comment]
Inspired by your feedback I have distributed my timers over different flows and did rename them. It is now running for 2days and I have not seen any timer halted.

thx for your help .. This workaround is fine more me
________________________________

**Comment by linuxha** [comment]
I've attempted to test with all 12 nodes being fed by the same input topic (with each output on it's own topic). Not seeing the issue yet. So I'll now move on to each timer getting it's own input as well as output and start sending the more complex input (each timer getting it's own json and hope I can randomize it to some extent).

Also posted a question on Discourse for Node-Red and the folks there have given me a few pointers. I'll work on there suggestions after a bit more testing.

**Comment by tsprivate** [comment]
Hi , as mentioned in my earlier mail I have distributed the timers over different flows and even renamed them .. I have not experienced the issue since ... at moment they are working perfectly fine
________________________________

**Comment by linuxha** [comment]
Understood, but I'm stubborn, the thought of a bug in my code haunts me ... and I'm fixing it so my wife never finds out about the bug because the timers didn't work.  Guess which one is more likely? ;-)

This one appears to be a coding issue with my use of locals instead of globals. The various language scope still confuse me.

**Comment by tsprivate** [comment]
Hi,
I have now 2 Node-Red installations running:

1) Hass.io & Node-Red (with previous version of myTimeout)  ==> working
2) Dedicated Node-Red (with latest version of myTimeout) ==> System freezes when timer is started

I installed the 2nd Node-Red system to improve the overall performance and remove some dependencies. It has the basic Raspbian+Nodered installation and all flows are migrated from first system.

After installation everything worked great. Until evening, than suddenly the Node-Red system was suddenly frozen. 
- I was able to login via SSH
- Node-red did not respond on events of via web-interface
- the command Node-red-stop than Node-red-start sometimes helped resuming service but not all the time (often I had to reboot)
- I installed the system 3 times because I assumed the SD cards had problems but always had the same issues

Because this drove me crazy, I decided to ignore the issue for a bit and do some new components for my light control. Doing so I was using your timer and realized that the system got frozen almost always when starting your timer.

![image](https://user-images.githubusercontent.com/41630517/44294205-ed231300-a2d6-11e8-9058-3b93dd95f0c5.png)

By removing the timer-component the flow works fine.

I did remove all your timer from the 2nd system yesterday afternoon and the system had no issue since.

I think there is a bug in your latest release...the previous version (which is still running on 1st system) works better for me

**Comment by linuxha** [comment]
On 08/17/2018 09:10 PM, tsprivate wrote:
> I think there is a bug in your latest release...the previous version (which is still 
> running on 1st system) works better for me

Wow, that is bad. What is the version number of the previous release that is
more stable? I'll need to see what the changes were.

-- 
Linux Home Automation         Neil Cherry       linuxha@linuxha.com
http://��v��xha.com/                         Main site
http://linuxha.blogspot.com/                    My HA Blog
Author of:    	Linux Smart Homes For Dummies

**Comment by tsprivate** [comment]
The stable version in 1st system is 2.1.4
The unstable version in 2nd system is 2.1.8

I just did a complete new install for 2nd system ...all flows migrated from 1st to 2nd .. the systems are now identical

**Error-situation:**
- Motion detector is triggering light on
- I can see the timer starting
- any other tickle to the timer makes the system freeze (i tried with off command) 

I tired Mitigation 1:
- removing all timers and replaced them with normal delay
- all works, no freeze

I tired Mitigation 2:
- I have all light-controls in a dedicated flow
- I disable the light-flow tab
- motion triggers are still detected but no light activities
- all works (without the lights)

I hope you can replicate the situation and i helps solving the issue

good luck

**Comment by tsprivate** [comment]
Feature request:

I usually need a decision node after the timer to evaluate the msg.payload for "on" or "off"

Would it be possible to have optional out-ports for on and off.. in addition to your current out-port ?

**Comment by linuxha** [comment]
For the feature request, I think a switch node would be the correct choice. I'm not even sure how I could work that feature into the existing code.

BTW, I also turned off (by default) all the debugging code. A check mark in the node config will turn it on for each node. I'm wondering if that code is at the source of the issue. I'll see shortly.

**Comment by tsprivate** [comment]
I have done a few more test .. and it looks like when I start the timer and let it run till the end without any further trigger (On/Off/new time) ... than everything works

It is only when I tickle/trigger the timer again that everything is freezing

**Comment by linuxha** [comment]
Thanks for the help. I've tried the latest mytimeout on one of my Pi look a-likes (need to find the stuff for a Pi setup. I have:

18 Aug 19:19:43 - [info] Node-RED version: v0.19.1
18 Aug 19:19:43 - [info] Node.js  version: v8.11.4
18 Aug 19:19:43 - [info] Linux 3.8.13.30 arm LE

Installing module: node-red-contrib-mytimeout, version: 2.1.8

I setup a timer with one injection and one debug. It works with on and let run & on - on - on and it works. I'll try some more. Can you do the following:

sum mytimeout.js # for both 2.1.4 and 2.1.8 

I'm dropping in your flow from above and I'll try that out also.

**Comment by tsprivate** [comment]
Good morning,

what do you mean by

sum mytimeout.js # for both 2.1.4 and 2.1.8 ?

I'm happy to do so as soon I'm back home this afternoon.

I'm currently browsing forums in regards of "Node-red not responsive/freeze" and I have seen that this is often happening when the Home-Assistant component is connected via SSL (routed via internet ..not local) .. which is the case for me too.

However, there was no service-call to Home-Assistant activated in the flow I shared with you earlier... and since I have removed the myTimeout with delay-nodes I had no freeze at all.

This afternoon, I will do some further timer testing with more simple Timer flows.
________________________________

**Comment by linuxha** [comment]
Sorry, those are Linux commands, so you'd run them from the command prompt. As the user who started nod-red do (command line/command prompt):

cd ~/.node-red/node_modules/node-red-contrib-mytimeout
sum mytimeout.js

On a side note, I ran your code above. I am missing the time range and the light state node but I don't think they're needed for this test.

When I finished the setup I notice that the 'flows' stop because the lack of a server setting 

18 Aug 19:53:47 - [info] Waiting for missing types to be registered:
18 Aug 19:53:47 - [info]  - server
18 Aug 19:54:48 - [info] Stopping flows

I don't know what this means at this point but I'll search for that. I don't think that is related to mytimeout. It may be related to my current setup.

**Comment by linuxha** [comment]
Okay, I know exactly what is going on. Your basically feeding the output to the timer to the input of the timer. This feedback is keeping NR so busy that NR can't respond. There was a change between 2.1.4 and 2.1.5 that made to handle this differently. I'll need to have a good look at this. Not sure how to handle this. The problem with 2.1.4 is that if you sent on On and several days later sent another On then the 2nd On gets dropped (probably indefinite hold of the last message sent).

**Comment by linuxha** [comment]
Next question, do you intend to continuously send the commands back into the loop?

**Comment by tsprivate** [comment]
Damn, yes you are right .. I created a loop for the off command :( .. no, that was not intentional

I created the loop to update the dashboard-ui button to OFF when the timer completed :( .. I will have to change that code.

Thanks for helping with my issue that fast

**Comment by linuxha** [comment]
I think you can add a delay note, set it to rate limit, 1 msg / 1 second and drop immediate messages. Add it to the link in @TS Off. I think that should work. I think the reason mytimeout node isn't handling it is because the case of the message changes. the node sends off and the incoming is set to OFF. I'll see about adding a case insensitive option. Need to give that some thought.

**Comment by linuxha** [comment]
The latest code has the msg handling fix and an option to ignore case on input match. This might help a little bit on sedning the output to the input. I tried to handle that issue because it's useful to send the output to the ui_switch so you can match the controlled device's state. I think your code  was changing the case so it didn't match. There are some other updates to the code to clean up the handling and some kruft that was in the code. I still need to update the documentation and open an issue on a error message the can be ignored:

**"The workspace contains some nodes that are not properly configured: ... are you sure you want to deploy."**

You can deploy it's harmless and I have a manual fix but I need to figure out how to word it.

**Comment by jeffheartmp** [comment]
found this while browsing an unrelated bug, what an awesome exchange between you too
